name: Workflow / Check the accessibility
run-name: ${{ github.actor }} is testing accessibility 
on: [push]

jobs:
  check-accessibility-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello man!"
